Samara/Controllers/ManageController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Samara.Models;

//made in the new NTHR
namespace Samara.Controllers
{
    [Authorize]
    public class ManageController : EAController
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ManageController()
        {
        }

        public ManageController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Manage/Index
        public async Task<ActionResult> Index(ManageMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ManageMessageId.ChangePasswordSuccess ? "Your password has been changed."
                : message == ManageMessageId.SetPasswordSuccess ? "Your password has been set."
                : message == ManageMessageId.SetTwoFactorSuccess ? "Your two-factor authentication provider has been set."
                : message == ManageMessageId.Error ? "An error has occurred."
                : message == ManageMessageId.AddPhoneSuccess ? "Your phone number was added."
                : message == ManageMessageId.RemovePhoneSuccess ? "Your phone number was removed."
                : "";

            var userId = User.Identity.GetUserId();
            var model = new IndexViewModel
            {
                HasPassword = HasPassword(),
                PhoneNumber = await UserManager.GetPhoneNumberAsync(userId),
                TwoFactor = await UserManager.GetTwoFactorEnabledAsync(userId),
                Logins = await UserManager.GetLoginsAsync(userId),
                BrowserRemembered = await AuthenticationManager.TwoFactorBrowserRememberedAsync(userId)
            };
            return View(model);
        }

        //
        // POST: /Manage/RemoveLogin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveLogin(string loginProvider, string providerKey)
        {
            ManageMessageId? message;
            var result = await UserManager.RemoveLoginAsync(User.Identity.GetUserId(), new UserLoginInfo(loginProvider, providerKey));
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                message = ManageMessageId.RemoveLoginSuccess;
            }
            else
            {
                message = ManageMessageId.Error;
            }
            return RedirectToAction("ManageLogins", new { Message = message });
        }

        //
        // GET: /Manage/AddPhoneNumber
        public ActionResult AddPhoneNumber()
        {
            return View();
        }

        //
        // POST: /Manage/AddPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddPhoneNumber(AddPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            // Generate the token and send it
            var code = await UserManager.GenerateChangePhoneNumberTokenAsync(User.Identity.GetUserId(), model.Number);
            if (UserManager.SmsService != null)
            {
                var message = new IdentityMessage
                {
                    Destination = model.Number,
                    Body = "Your security code is: " + code
                };
                await UserManager.SmsService.SendAsync(message);
            }
            return RedirectToAction("VerifyPhoneNumber", new { PhoneNumber = model.Number });
        }

        //
        // POST: /Manage/EnableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EnableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), true);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //
        // POST: /Manage/DisableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DisableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), false);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //
        // GET: /Manage/VerifyPhoneNumber
        public async Task<ActionResult> VerifyPhoneNumber(string phoneNumber)
        {
            var code = await UserManager.GenerateChangePhoneNumberTokenAsync(User.Identity.GetUserId(), phoneNumber);
            // Send an SMS through the SMS provider to verify the phone number
            return phoneNumber == null ? View("Error") : View(new VerifyPhoneNumberViewModel { PhoneNumber = phoneNumber });
        }

        //
        // POST: /Manage/VerifyPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyPhoneNumber(VerifyPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await UserManager.ChangePhoneNumberAsync(User.Identity.GetUserId(), model.PhoneNumber, model.Code);
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                return RedirectToAction("Index", new { Message = ManageMessageId.AddPhoneSuccess });
            }
            // If we got this far, something failed, redisplay form
            ModelState.AddModelError("", "Failed to verify phone");
            return View(model);
        }

        //
        // POST: /Manage/RemovePhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemovePhoneNumber()
        {
            var result = await UserManager.SetPhoneNumberAsync(User.Identity.GetUserId(), null);
            if (!result.Succeeded)
            {
                return RedirectToAction("Index", new { Message = ManageMessageId.Error });
            }
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", new { Message = ManageMessageId.RemovePhoneSuccess });
        }

        //
        // GET: /Manage/ChangePassword
        public ActionResult ChangePassword()
        {
            return View();
        }

        //
        // POST: /Manage/ChangePassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await UserManager.ChangePasswordAsync(User.Identity.GetUserId(), model.OldPassword, model.NewPassword);
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                return RedirectToAction("Index", new { Message = ManageMessageId.ChangePasswordSuccess });
            }
            AddErrors(result);
            return View(model);
        }

        //
        // GET: /Manage/SetPassword
        public ActionResult SetPassword()
        {
            return View();
        }

        //
        // POST: /Manage/SetPassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SetPassword(SetPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await UserManager.AddPasswordAsync(User.Identity.GetUserId(), model.NewPassword);
                if (result.Succeeded)
                {
                    var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                    if (user != null)
                    {

Samara/Controllers/SupplierBillController.cs
using Microsoft.AspNet.Identity;
using System;
//using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
//using System.Web;
using System.Web.Mvc;


namespace Samara.Controllers
{
    public class SupplierBillController : EAController
    {
        public ActionResult Index(int? page, string SupplierName)
        {
            if (SupplierName?.Length > 0) page = 1;
            return View("Index", base.BaseIndex<SuppDet>(page, "SBillID,SupplierName,SiteName, Tdate", "SupplierBill as sb Inner Join Supplier as s on sb.SupplierID = s.SupplierID inner join Sites st on sb.SiteID = st.SiteID where SupplierName like '%" + SupplierName + "%'"));
        }



        // GET: Clients/Create
        public ActionResult Manage(int? id)
        {
            ViewBag.SupplierID = new SelectList(db.Fetch<Supplier>("Select SupplierID,SupplierName from Supplier"), "SupplierID", "SupplierName");

            return View(base.BaseCreateEdit<SupplierBill>(id, "SBillID"));
        }


        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Manage([Bind(Include = "SBillID,SupplierID,SiteID,Tdate")] SupplierBill supplierBill)
        {
            supplierBill.TDSperc =(decimal) db.FirstOrDefault<Config>("Select TDSperc from Config").TDSperc;
            return base.BaseSave<SupplierBill>(supplierBill, supplierBill.SBillID > 0);
        }

        public ActionResult Details(int? id)
        {
            
             var viewdata = new Suplier_Bill
             {
                        SuplierDets = db.FirstOrDefault<SuppDet>("Select SBillID,SupplierName,Tdate,TDSperc from SupplierBill as sb Inner Join Supplier as s on sb.SupplierID =s.SupplierID where SBillID = @0", id),
                        SuplierBillDets = db.Fetch<SuppBillDet>("Select * From SupplierBillDetail sbd inner join Labour l on sbd.LabourID = l.LabourID Where SBillID = @0", id)
                 
            };
            ViewBag.LabourID = new SelectList(db.Fetch<Labour>("Select LabourID,LabourName from Labour"), "LabourID", "LabourName");
            ViewBag.tds = db.FirstOrDefault<decimal>("Select TDSperc from Config");
            ViewBag.SBillID = id;
            return View("Details", viewdata);            
        }
  
        [HttpPost]     
        public ActionResult Details([Bind(Include = "SBillDetailID,SBillID,LabourID,Job,Qty,UnitPrice,QtyRec,QtySold")] SupplierBillDetail supplierBillDetail)
        {
            var GetItem = db.FirstOrDefault<SupplierBillDetail>("Select * From SupplierBillDetail Where LabourID=@0 and SBillID =@0", supplierBillDetail.LabourID,supplierBillDetail.SBillID);
            if(GetItem ==  null)
            {
         
                supplierBillDetail.QtyRec = 0;
                ViewBag.Total = db.Fetch<SupplierBillDetail>("");
              base.BaseSave<SupplierBillDetail>(supplierBillDetail, supplierBillDetail.SBillDetailID > 0);
              
            }
            else
            {
                db.Update("SupplierBillDetail", "SBillDetailID", new { Qty = GetItem.Qty + supplierBillDetail.Qty ,UnitPrice =supplierBillDetail.UnitPrice }, GetItem.SBillDetailID);
            }

      
        
            return RedirectToAction("Details",new {id=supplierBillDetail.SBillID });
        }

        public ActionResult ManageDetails(int? id)
        {
            ViewBag.SupBillDets = base.BaseCreateEdit<SupplierBillDetail>(id, "SBillDetailID");
            ViewBag.LabourName = db.FirstOrDefault<SuppBillDet>("Select LabourName From SupplierBillDetail sbd inner  join  labour as l on sbd.LabourID = l.LabourID where SBillDetailID= @0", id).LabourName;
            ViewBag.tds = db.FirstOrDefault<decimal>("Select TDSperc from Config");
            var viewdata = new Suplier_Bill
                {
                    SuplierDets = db.FirstOrDefault<SuppDet>("Select SBillID,SupplierName,Tdate,TDSperc from SupplierBill as sb Inner Join Supplier as s on sb.SupplierID =s.SupplierID where SBillID = @0", id),
                    SuplierBillDets = db.Fetch<SuppBillDet>("Select * From SupplierBillDetail  Where SBillID = @0", id)
                };
              
               
                return View("Details", viewdata);            
        }
  
        [HttpPost]     
        public ActionResult ManageDetails([Bind(Include = "SBillDetailID,SBillID,LabourID,Job,Qty,UnitPrice,QtyRec,QtySold")] SuppBillDet supplierBillDetail)
        {
            var objToSave = new SupplierBillDetail()
            {
                SBillDetailID = supplierBillDetail.SBillDetailID,
                SBillID = supplierBillDetail.SBillID,
                LabourID = supplierBillDetail.LabourID,
                Job = supplierBillDetail.Job,
                Qty = supplierBillDetail.Qty,
                UnitPrice = supplierBillDetail.UnitPrice,
                QtyRec = supplierBillDetail.QtyRec,
                QtySold = supplierBillDetail.QtySold
            };

            base.BaseSave<SupplierBillDetail>(objToSave, supplierBillDetail.SBillDetailID > 0);
       
            return RedirectToAction("Details",new { id = supplierBillDetail.SBillID });
        }


        public ActionResult AutoCompleteSite(string term)
        {
            string UserID = User.Identity.GetUserId();
            var h = db.Fetch<AutoCompleteData>($"Select ss.SiteID as id, SiteName as value from SupervisorSites as ss Inner Join Sites s on s.SiteID = ss.SiteID inner join AspNetUsers anu on ss.UserID=anu.Id Where SiteName like '%{term}%' and ss.UserID = @0 ", UserID).ToList();
            return Json(h, JsonRequestBehavior.AllowGet);
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Samara/Views/SupplierBill/Details.cshtml
@model Samara.Suplier_Bill
@using PagedList.Mvc;
@{
    ViewBag.Title = "Contractor Details";
}

    <center>
        <h2 class="section-to-print"><b>@ViewBag.Title</b></h2>



        <table class="table-condensed section-to-NOT-print">

            @using (@Html.BeginForm())
            {
                if (ViewBag.supBillDets != null)
                {
                    @Html.Hidden("SBillID", (int)ViewBag.SupBillDets.SBillID)

                    @Html.Hidden("SBillDetailID", (int)ViewBag.SupBillDets.SBillDetailID)
                    <tr>
                        <td>@Html.Label("Labour")</td>
                        <td>@Html.Label((string)ViewBag.LabourName, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td>@Html.Label("Quantity")</td>
                        <td>@Html.TextBox("Qty", (int)ViewBag.SupBillDets.Qty, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td>@Html.Label("Unit Price")</td>

                        <td>@Html.TextBox("UnitPrice", (decimal)ViewBag.SupBillDets.UnitPrice, new { @class = "form-control" })</td>
                    </tr>
                }
                else
                {
                    if (ViewBag.SBillID != null)
                    {
                        @Html.Hidden("SBillID", (int)ViewBag.SBillID)
                    }

                    <tr class="section-to-print">
                        <td class="col-md-4">Contractor Name:</td>
                        <td class="col-md-4">@Html.DisplayFor(modelItem => Model.SuplierDets.SupplierName)</td>
                    </tr>
                    <tr class="section-to-print">
                        <td class="col-md-4">Date:</td>
                        <td class="col-md-4">@Html.DisplayFor(modelItem => Model.SuplierDets.Tdate)</td>
                    </tr>

                    <tr>
                        <td>@Html.Label("Labour")</td>
                        <td>@Html.DropDownList("LabourID", null, new { @class = "form-control" })</td>

                    </tr>
                    <tr>
                        <td>@Html.Label("Quantity")</td>
                        <td>@Html.Editor("Qty", new { htmlAttributes = new { @class = "form-control" } })</td>
                    </tr>
                    <tr>
                        <td>@Html.Label("Unit Price")</td>
                        <td>@Html.Editor("UnitPrice", new { htmlAttributes = new { @class = "form-control" } })</td>
                    </tr>
                }
                <tr>
                    <td><input action="action" onclick="window.history.go(-1); return false;" type="button" value="Back" /></td>

                    <td><input type="submit" value="Submit" /></td>
                </tr>
            }
        </table>
    </center>
    <br />
    @if (ViewBag.supBillDets == null)
    {
        <table class="table section-to-print">
            <tr>
                <th>
                    Sr No
                </th>

                <th>
                    Labour
                </th>
                <th>
                    Qty
                </th>
                <th>
                    Unit Price
                </th>
                <th>
                    Amount
                </th>


                <th class="section-to-Not-print">
                    <input type="button" onclick="javascript:window.print();" value="Print" class="eabutton section-to-not-print" />
                </th>

            </tr>
            @{int i = 1; decimal tot = 0; }

            @foreach (var item in Model.SuplierBillDets)
            {
                <tr>
                    <td>
                        @i
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.LabourName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Qty)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnitPrice)
                    </td>


                    <td>
                        @{ decimal amt = item.Qty * item.UnitPrice;
                            tot = tot + amt;

                        }
                        @amt
                    </td>

                    <td class="section-to-Not-print">
                        @Html.ActionLink("Edit", "ManageDetails", new { id = item.SBillDetailID })
                    </td>
                </tr>

                                i++;
                            }

            <tr>

                <td>
                    Tax:
                </td>
                <td>
                <td>
                <td></td>
                <td>
                    @{ decimal Tax = tot * ViewBag.tds / 100;}
                    @Tax
                </td>
            </tr>
            <tr>

                <td>
                    Total Amount:
                </td>
                <td>
                <td>
                <td></td>
                <td>
                    @{decimal orig = tot - Tax;}


                    @orig
                </td>
            </tr>
        </table>


     }

Samara/Views/SupplierBill/Index.cshtml
@model PagedList.IPagedList<Samara.SuppDet>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Contractor Bills";
}

<center>
    <h2 class="section-to-print"><b>@ViewBag.Title</b></h2>
    
    @using (Html.BeginForm("Index", "SupplierBill", FormMethod.Get))
    {        
        <div class="row section-to-Not-print">
            <div>
                <table>
                    <tr style="text-align:center">
                        <td>&nbsp; Contractor Name:</td>
                        <td> @Html.TextBox("SupplierName", ViewBag.CurrentFilter as string, new { @class = "form-control" })</td>

                        <td class="col-lg-1"></td>
                        <td><input type="submit" value="Search" class="btn btn-default" /></td>
                    </tr>
                </table>
            </div>
        </div>
    }
</center>

<p>
    @Html.ActionLink("Create New", "Manage")
</p>
<table class="table">
    <tr>
        <th>
            Sr No
        </th>
        <th>
            Contractor Name
        </th>
        <th>
            Site 
        </th>
        <th>
           @Html.DisplayNameFor(modelItem => modelItem.FirstOrDefault().Tdate)
        </th>
       
        <th></th>

    </tr>
    @{int i = 1; }
@foreach (var item in Model) {
    <tr>
        <td>
           @i
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SupplierName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SiteName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tdate)
        </td>
    
        <td>
            @Html.ActionLink("Edit", "Manage", new { id=item.SBillID }) |@Html.ActionLink("Details", "Details", new { id = item.SBillID })
            
        </td>
    </tr>
    i++;
}

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

Samara/Views/SupplierBill/Manage.cshtml
@model SupplierBill

@{
    ViewBag.Title = "Manage";
}

<h2>Manage</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.SiteID)

    <div class="form-horizontal">
        <h4>Supplier Bill</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (Model?.SBillID >0)
        {
            @Html.HiddenFor(model => model.SBillID)
        }
   
        <div class="form-group">
            @Html.LabelFor(model => model.SupplierID, "Supplier", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SupplierID, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">            
            @Html.LabelFor(model => model.Tdate, "Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tdate, new { htmlAttributes = new { @class = "form-control" ,@type ="date"} })
                @Html.ValidationMessageFor(model => model.Tdate, "", new { @class = "text-danger" })
            </div>
        </div>

       <div class="form-group"> 
        @Html.LabelFor(model => model.SiteID,"Site", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" id="SiteName" name="SiteName" style="color:black;" data-autocomplete-idholder="#SiteID" data-autocombo-url="@Url.Action("AutoCompleteSite")" class="form-control" />
            @Html.ValidationMessageFor(model => model.SiteID, "", new { @class = "text-danger" })
        </div>
    </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}